# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: AzurePowerShell@5
  inputs:
    azureSubscription: 'armpipeline-conn'
    ScriptType: 'FilePath'
    ScriptPath: 'CreateBlob/azuredeploy.json'
    ScriptArguments: '-projectName armpipeline'
    azurePowerShellVersion: 'LatestVersion'
